export const TODAY = new Date().toISOString().slice(0, 10);

export function isOverdue(dueDate, status) {
  if (status === "Zrobione" || status === "Ukończony") return false;
  return dueDate < TODAY;
}

// ── Klienci (jeden punkt prawdy – powiązani z projektami przez clientId) ──
export const mockClients = [
  {
    id: "cl-1",
    name: "Jan Kowalski",
    company: null,
    email: "j.kowalski@gmail.com",
    phone: "+48 601 234 567",
    source: "Polecenie",
    pipelineStatus: "Realizacja",
    createdDate: "2026-01-15",
    notes: "Klient wymaga cotygodniowych raportów postępu.",
    isArchived: false,
  },
  {
    id: "cl-2",
    name: "Anna Nowak",
    company: null,
    email: "a.nowak@gmail.com",
    phone: "+48 602 345 678",
    source: "Inne",
    pipelineStatus: "Wycena",
    createdDate: "2025-12-10",
    notes: "Wstrzymany – klient oczekuje na decyzję architekta.",
    isArchived: false,
  },
  {
    id: "cl-3",
    name: "Piotr Wiśniewski",
    company: null,
    email: "p.wisniewski@gmail.com",
    phone: "+48 603 456 789",
    source: "Polecenie",
    pipelineStatus: "Realizacja",
    createdDate: "2026-01-20",
    notes: "",
    isArchived: false,
  },
  {
    id: "cl-4",
    name: "Tomasz Malinowski",
    company: "Malinowski Sp. z o.o.",
    email: "t.malinowski@gmail.com",
    phone: "+48 604 567 890",
    source: "Inne",
    pipelineStatus: "Realizacja",
    createdDate: "2025-11-05",
    notes: "Projekt komercyjny – biuro 5 kondygnacji.",
    isArchived: false,
  },
  {
    id: "cl-5",
    name: "Marek Zieliński",
    company: null,
    email: "m.zielinski@gmail.com",
    phone: "+48 605 678 901",
    source: "Polecenie",
    pipelineStatus: "Zakończony",
    createdDate: "2025-09-15",
    notes: "Projekt zakończony. Klient bardzo zadowolony.",
    isArchived: true,
  },
  {
    id: "cl-6",
    name: "Karolina Dąbrowska",
    company: null,
    email: "k.dabrowska@gmail.com",
    phone: "+48 606 789 012",
    source: "Inne",
    pipelineStatus: "Lead",
    createdDate: "2026-02-20",
    notes: "Zainteresowana pakietem Full house. Dom jednorodzinny, Kraków.",
    isArchived: false,
  },
  {
    id: "cl-7",
    name: "Michał Kaźmierczak",
    company: "KaźTech Biura",
    email: "m.kazmierczak@gmail.com",
    phone: "+48 607 890 123",
    source: "Konfigurator",
    pipelineStatus: "Wycena",
    createdDate: "2026-02-28",
    notes: "Budynek biurowy – 3 kondygnacje, automatyka KNX.",
    isArchived: false,
  },
];

// ── Projekty (używają clientId zamiast embedded client object) ──
export const mockProjects = [
  {
    id: "proj-1",
    clientId: "cl-1",
    code: "KOW-2026-001",                    // ← unikalny kod projektu (używany przez panel klienta i GAS Drive)
    name: "Dom Kowalski – Kraków",
    package: "Full house",
    status: "W trakcie",
    stageIndex: 3,
    stages: ["Wycena", "Projekt automatyki", "Projekt szafy", "Prefabrykacja", "Montaż", "Uruchomienie", "Szkolenie", "Odbiór"],
    stageSchedule: [                          // ← harmonogram etapów do Gantt
      { name: "Wycena",              start: "2026-02-01", end: "2026-02-07" },
      { name: "Projekt automatyki",  start: "2026-02-07", end: "2026-02-21" },
      { name: "Projekt szafy",       start: "2026-02-21", end: "2026-03-07" },
      { name: "Prefabrykacja",       start: "2026-03-07", end: "2026-03-28" },
      { name: "Montaż",              start: "2026-03-28", end: "2026-04-11" },
      { name: "Uruchomienie",        start: "2026-04-11", end: "2026-04-21" },
      { name: "Szkolenie",           start: "2026-04-21", end: "2026-04-25" },
      { name: "Odbiór",              start: "2026-04-25", end: "2026-04-30" },
    ],
    progress: 58,
    startDate: "2026-02-01",
    deadline: "2026-04-30",
    budget: 85000,
    address: "ul. Różana 12, Kraków",
    scope: "Kompleksowa automatyka budynkowa – system Loxone, sterowanie oświetleniem (120 pkt), roletami (24 szt.), ogrzewaniem podłogowym (12 stref), alarm Satel INTEGRA, integracja z PV.",
    profitProjekt: 14000,
    profitPrefabrykacja: 38000,
    profitUruchomienie: 18000,
    paidProjekt: 14000,
    paidPrefabrykacja: 19000,
    paidUruchomienie: 0,
    invoices: [
      { id: "inv-1-1", name: "FV 2026/02/001", amount: 14000, stageKey: "projekt",       date: "2026-02-10", url: "#" },
      { id: "inv-1-2", name: "FV 2026/03/002", amount: 19000, stageKey: "prefabrykacja", date: "2026-03-08", url: "#" },
    ],
    notes: "Klient wymaga cotygodniowych raportów postępu.",
    tags: ["priorytet", "full house"],
  },
  {
    id: "proj-2",
    clientId: "cl-2",
    code: "NOW-2026-001",
    name: "Apartament Nowak – Warszawa",
    package: "Smart design+",
    status: "Wstrzymany",
    stageIndex: 1,
    stages: ["Wycena", "Projekt automatyki", "Projekt szafy", "Prefabrykacja", "Uruchomienie"],
    stageSchedule: [
      { name: "Wycena",              start: "2026-01-15", end: "2026-01-22" },
      { name: "Projekt automatyki",  start: "2026-01-22", end: "2026-03-15" },   // wstrzymany
      { name: "Projekt szafy",       start: "2026-03-15", end: "2026-04-05" },
      { name: "Prefabrykacja",       start: "2026-04-05", end: "2026-04-25" },
      { name: "Uruchomienie",        start: "2026-04-25", end: "2026-05-31" },
    ],
    progress: 20,
    startDate: "2026-01-15",
    deadline: "2026-05-31",
    budget: 45000,
    address: "ul. Marszałkowska 7/4, Warszawa",
    scope: "Smart home w apartamencie – sterowanie oświetleniem (60 pkt), roletami (10 szt.), ogrzewaniem (4 strefy), audio multi-room Sonos.",
    profitProjekt: 8000,
    profitPrefabrykacja: 22000,
    profitUruchomienie: 10000,
    paidProjekt: 8000,
    paidPrefabrykacja: 0,
    paidUruchomienie: 0,
    invoices: [
      { id: "inv-2-1", name: "FV 2026/01/003", amount: 8000, stageKey: "projekt", date: "2026-01-22", url: "#" },
    ],
    notes: "Wstrzymany – klient oczekuje na decyzję architekta.",
    tags: [],
  },
  {
    id: "proj-3",
    clientId: "cl-3",
    code: "WIS-2026-001",
    name: "Dom Wiśniewski – Wrocław",
    package: "Smart design",
    status: "W trakcie",
    stageIndex: 2,
    stages: ["Wycena", "Projekt automatyki", "Projekt szafy", "Odbiór"],
    stageSchedule: [
      { name: "Wycena",              start: "2026-02-10", end: "2026-02-17" },
      { name: "Projekt automatyki",  start: "2026-02-17", end: "2026-02-28" },
      { name: "Projekt szafy",       start: "2026-02-28", end: "2026-03-18" },
      { name: "Odbiór",              start: "2026-03-18", end: "2026-03-31" },
    ],
    progress: 45,
    startDate: "2026-02-10",
    deadline: "2026-03-31",
    budget: 22000,
    address: "ul. Lipowa 5, Wrocław",
    scope: "Podstawowa automatyka domu jednorodzinnego – Loxone Compact, sterowanie oświetleniem (45 pkt), ogrzewaniem (6 stref), bramą garażową.",
    profitProjekt: 4500,
    profitPrefabrykacja: 11000,
    profitUruchomienie: 5500,
    paidProjekt: 4500,
    paidPrefabrykacja: 0,
    paidUruchomienie: 0,
    invoices: [
      { id: "inv-3-1", name: "FV 2026/02/004", amount: 4500, stageKey: "projekt", date: "2026-02-17", url: "#" },
    ],
    notes: "",
    tags: [],
  },
  {
    id: "proj-4",
    clientId: "cl-4",
    code: "MAL-2025-001",
    name: "Biuro Malinowski – Gdańsk",
    package: "Full house",
    status: "W trakcie",
    stageIndex: 4,
    stages: ["Wycena", "Projekt", "Prefabrykacja", "Montaż", "Uruchomienie", "Odbiór"],
    stageSchedule: [
      { name: "Wycena",              start: "2025-12-01", end: "2025-12-10" },
      { name: "Projekt automatyki",  start: "2025-12-10", end: "2026-01-05" },
      { name: "Prefabrykacja",       start: "2026-01-05", end: "2026-01-25" },
      { name: "Montaż",              start: "2026-01-25", end: "2026-02-18" },
      { name: "Uruchomienie",        start: "2026-02-18", end: "2026-03-10" },
      { name: "Odbiór",              start: "2026-03-10", end: "2026-03-20" },
    ],
    progress: 60,
    startDate: "2025-12-01",
    deadline: "2026-03-20",
    budget: 120000,
    address: "ul. Długa 1, Gdańsk",
    scope: "Automatyka komercyjna biura 5-kondygnacyjnego – KNX, sterowanie oświetleniem (300 pkt DALI), klimatyzacją (20 stref VRF), żaluzjami fasadowymi, BMS, integracja z systemem kontroli dostępu.",
    profitProjekt: 22000,
    profitPrefabrykacja: 58000,
    profitUruchomienie: 25000,
    paidProjekt: 22000,
    paidPrefabrykacja: 58000,
    paidUruchomienie: 12500,
    invoices: [
      { id: "inv-4-1", name: "FV 2025/12/010", amount: 22000, stageKey: "projekt",       date: "2025-12-10", url: "#" },
      { id: "inv-4-2", name: "FV 2026/01/011", amount: 58000, stageKey: "prefabrykacja", date: "2026-01-25", url: "#" },
      { id: "inv-4-3", name: "FV 2026/02/015", amount: 12500, stageKey: "uruchomienie",  date: "2026-02-18", url: "#" },
    ],
    notes: "Projekt komercyjny – biuro 5 kondygnacji.",
    tags: ["komercyjny", "priorytet"],
  },
  {
    id: "proj-5",
    clientId: "cl-5",
    code: "ZIE-2025-001",
    name: "Dom Zieliński – Poznań",
    package: "Smart design+",
    status: "Ukończony",
    stageIndex: 4,
    stages: ["Wycena", "Projekt", "Szafa", "Montaż", "Uruchomienie"],
    stageSchedule: [
      { name: "Wycena",              start: "2025-10-01", end: "2025-10-10" },
      { name: "Projekt",             start: "2025-10-10", end: "2025-11-01" },
      { name: "Szafa",               start: "2025-11-01", end: "2025-12-01" },
      { name: "Montaż",              start: "2025-12-01", end: "2026-01-10" },
      { name: "Uruchomienie",        start: "2026-01-10", end: "2026-01-31" },
    ],
    progress: 100,
    startDate: "2025-10-01",
    deadline: "2026-01-31",
    budget: 38000,
    address: "ul. Kwiatowa 22, Poznań",
    scope: "Smart design+ dla domu jednorodzinnego – Loxone, oświetlenie (80 pkt), rolety (16 szt.), ogrzewanie (8 stref), rekuperacja, wizualizacja Loxone App.",
    profitProjekt: 7000,
    profitPrefabrykacja: 18000,
    profitUruchomienie: 8000,
    paidProjekt: 7000,
    paidPrefabrykacja: 18000,
    paidUruchomienie: 8000,
    invoices: [
      { id: "inv-5-1", name: "FV 2025/10/020", amount: 7000,  stageKey: "projekt",       date: "2025-10-10", url: "#" },
      { id: "inv-5-2", name: "FV 2025/11/021", amount: 18000, stageKey: "prefabrykacja", date: "2025-11-01", url: "#" },
      { id: "inv-5-3", name: "FV 2026/01/025", amount: 8000,  stageKey: "uruchomienie",  date: "2026-01-31", url: "#" },
    ],
    notes: "Projekt zakończony. Klient bardzo zadowolony.",
    tags: [],
  },
];

export const mockTasks = [
  { id: "t1",  type: "task",  projectId: "proj-1", title: "Schemat szafy sterowniczej – v2",     assignee: "Adam", status: "Niezrobione", priority: "Wysoki",    dueDate: "2026-03-05", description: "Przygotować schemat elektryczny szafy sterowniczej." },
  { id: "t2",  type: "task",  projectId: "proj-1", title: "Zamówienie kabli – lista BOM",         assignee: "Adam", status: "Niezrobione", priority: "Normalny",   dueDate: "2026-03-10", description: "Przygotować listę materiałową i złożyć zamówienie." },
  { id: "t3",  type: "task",  projectId: "proj-3", title: "Projekt automatyki – dom Wiśniewski",  assignee: "Adam", status: "Zrobione",    priority: "Normalny",   dueDate: "2026-02-28", description: "Projekt gotowy, przesłany do klienta." },
  { id: "t4",  type: "task",  projectId: "proj-4", title: "Wycena dodatkowych modułów I/O",       assignee: "Adam", status: "Niezrobione", priority: "Wysoki",    dueDate: "2026-03-02", description: "Klient zapytał o 4 dodatkowe moduły wejść/wyjść." },
  { id: "t5",  type: "task",  projectId: "proj-2", title: "Kontakt z architektem – Nowak",        assignee: "Adam", status: "Niezrobione", priority: "Niski",     dueDate: "2026-03-15", description: "Uzgodnić zmiany w projekcie po decyzji architekta." },
  { id: "t6",  type: "task",  projectId: "proj-4", title: "Programowanie sterownika Loxone",      assignee: "Adam", status: "Niezrobione", priority: "Krytyczny", dueDate: "2026-03-01", description: "Zakończenie programowania logiki sterowania biura." },
  { id: "t7",  type: "task",  projectId: "proj-1", title: "Integracja alarmu Satel z Loxone",     assignee: "Adam", status: "Niezrobione", priority: "Wysoki",    dueDate: "2026-03-20", description: "Integracja systemu alarmowego Satel z miniServerem." },
  { id: "t8",  type: "task",  projectId: "proj-3", title: "Aktualizacja oferty – Wiśniewski",     assignee: "Adam", status: "Niezrobione", priority: "Normalny",  dueDate: "2026-03-08", description: "Zaktualizować ofertę o dodatkowe gniazdka." },
  { id: "t9",  type: "task",  projectId: null,     title: "Przygotować szkolenie KNX",            assignee: "Adam", status: "Niezrobione", priority: "Normalny",  dueDate: "2026-03-10", description: "Szkolenie z obsługi ETS i topologii KNX." },
  { id: "t10", type: "task",  projectId: null,     title: "Aktualizacja szablonów dokumentów",    assignee: "Adam", status: "Niezrobione", priority: "Niski",     dueDate: "2026-03-20", description: "Zaktualizować szablony Excel i Word do nowego brandu." },
  // Wydarzenia
  { id: "e1",  type: "event", projectId: "proj-1", title: "Spotkanie z klientem Kowalski",        assignee: "Adam", status: "Niezrobione", priority: "Normalny",  dueDate: "2026-03-05", description: "Omówienie postępu prac i harmonogramu prefabrykacji." },
  { id: "e2",  type: "event", projectId: null,     title: "Webinar KNX – ETS5 online",            assignee: "Adam", status: "Niezrobione", priority: "Normalny",  dueDate: "2026-03-10", description: "Szkolenie online z topologii KNX i konfiguracji ETS5." },
  { id: "e3",  type: "event", projectId: "proj-4", title: "Odbiór techniczny – biuro Gdańsk",     assignee: "Adam", status: "Niezrobione", priority: "Normalny",  dueDate: "2026-03-03", description: "Finalny odbiór techniczny instalacji w biurze Malinowskiego." },
];

export const mockChecklists = [
  {
    id: "ch1",
    projectId: "proj-1",
    title: "Odbiór projektu automatyki",
    type: "etapowa",
    stage: "Etap 2",
    items: [
      { id: "chi1", text: "Weryfikacja listy punktów pomiarowych", done: true },
      { id: "chi2", text: "Sprawdzenie topologii sieci", done: true },
      { id: "chi3", text: "Weryfikacja programu Loxone Config", done: false },
      { id: "chi4", text: "Akceptacja klienta", done: false },
    ],
  },
  {
    id: "ch2",
    projectId: "proj-1",
    title: "Kontrola jakości szafy sterowniczej",
    type: "etapowa",
    stage: "Etap 3",
    items: [
      { id: "chi5", text: "Weryfikacja okablowania wewnętrznego", done: false },
      { id: "chi6", text: "Pomiar rezystancji izolacji", done: false },
      { id: "chi7", text: "Test zasilania UPS", done: false },
      { id: "chi8", text: "Oznaczenie kabli wg schematu", done: false },
      { id: "chi9", text: "Zdjęcia dokumentacyjne", done: false },
    ],
  },
  {
    id: "ch3",
    projectId: "proj-3",
    title: "Odbiór projektu – dom Wiśniewski",
    type: "projektowa",
    stage: "Finał",
    items: [
      { id: "chi10", text: "Projekt automatyki przekazany", done: true },
      { id: "chi11", text: "Projekt szafy przekazany", done: true },
      { id: "chi12", text: "Protokół odbioru podpisany", done: false },
      { id: "chi13", text: "Faktura wystawiona", done: false },
    ],
  },
  {
    id: "ch-g1",
    projectId: null,
    title: "Standardowa checklista uruchomienia Loxone",
    type: "globalna",
    stage: null,
    items: [
      { id: "chg1", text: "Firmware miniServera aktualny", done: false },
      { id: "chg2", text: "Konfiguracja sieci LAN / VLAN", done: false },
      { id: "chg3", text: "Test wszystkich wejść/wyjść", done: false },
      { id: "chg4", text: "Konfiguracja Loxone App na telefonie klienta", done: false },
      { id: "chg5", text: "Backup konfiguracji na Google Drive", done: false },
    ],
  },
  {
    id: "ch-g2",
    projectId: null,
    title: "Checklista przed oddaniem projektu elektrycznego",
    type: "globalna",
    stage: null,
    items: [
      { id: "chg6", text: "Schemat elektryczny zaktualizowany", done: false },
      { id: "chg7", text: "Lista BOM zgodna z projektem", done: false },
      { id: "chg8", text: "Certyfikaty urządzeń zebrane", done: false },
      { id: "chg9", text: "Dokumentacja archiwizowana na Drive", done: false },
    ],
  },
];

export const mockMaterials = [
  { id: "mat-1", title: "Dokumentacja Loxone Config 14", category: "Dokumentacje", device: "Loxone",       description: "Oficjalna dokumentacja oprogramowania Loxone Config v14 – wszystkie bloki funkcyjne", url: "https://www.loxone.com/pol/kb/", date: "2026-01-10" },
  { id: "mat-2", title: "Skrypt konfiguracji interfejsu KNX", category: "Skrypty", device: "KNX",          description: "Bash script do automatycznej konfiguracji interfejsu IP/USB KNX na Raspberry Pi", url: "#", date: "2026-01-20" },
  { id: "mat-3", title: "Instrukcja Satel INTEGRA 128-WRL", category: "Instrukcje", device: "Alarm",       description: "Instrukcja programowania i obsługi centrali alarmowej Satel INTEGRA 128", url: "#", date: "2026-02-01" },
  { id: "mat-4", title: "Kalkulator długości kabli (Excel)", category: "Skrypty", device: "",              description: "Arkusz Excel do obliczania długości kabli na podstawie rzutu budynku", url: "#", date: "2026-02-15" },
  { id: "mat-5", title: "Szablon schematu szafy sterowniczej", category: "Dokumentacje", device: "",       description: "Szablon schematu elektrycznego szafy sterowniczej – AutoCAD .dwg", url: "#", date: "2026-02-20" },
  { id: "mat-6", title: "Loxone HTTP API Reference", category: "Linki", device: "Loxone",                 description: "API do komunikacji z miniServerem przez HTTP/REST – odczyt i sterowanie punktami", url: "https://www.loxone.com/enen/kb/api/", date: "2026-03-01" },
];

export const mockProjectDocs = [
  { id: "pd-1", projectId: "proj-1", name: "Projekt automatyki v1.2.pdf", type: "pdf", description: "Projekt automatyki instalacji elektrycznej – rewizja 1.2", url: "#", date: "2026-02-10", clientVisible: true },
  { id: "pd-2", projectId: "proj-1", name: "Lista BOM – szafa sterownicza.xlsx", type: "xlsx", description: "Lista materiałów do szafy sterowniczej", url: "#", date: "2026-02-15", clientVisible: false },
  { id: "pd-3", projectId: "proj-1", name: "Schemat szafy v2.pdf", type: "pdf", description: "Schemat elektryczny szafy – rewizja 2", url: "#", date: "2026-02-20", clientVisible: false },
  { id: "pd-4", projectId: "proj-3", name: "Projekt automatyki Wiśniewski.pdf", type: "pdf", description: "Projekt automatyki – dom Wiśniewski, Wrocław", url: "#", date: "2026-02-28", clientVisible: true },
];
